### ISSUE TITLE
Please add a prefix to test-helper.el to avoid conflicts with 68 other packages

### ISSUE THREAD

**Issue by tarsius** [emacsorphanage/literate-coffee-mode#11]
There exist at least 69 packages that contain a file named `test-helper.el` that also provides the feature `test-helper`.

This leads to issues for users who have at least two of these packages installed.  It is unlikely that such a user would be able to run the tests of all of those packages.  If the primary test file of one of those packages does `(require 'test-helper)`, then it is undefined which of the various `test-helper.el` files gets loaded.  Which it is, depends on the order of the `load-path`.

To avoid this conflicts, you should rename your `test-helper.el` to `<your-package>-test-helper.el` and adjust the feature and symbol prefixes accordingly.

Also don't forget to update the `require` form in your primary test file and/or update references to the library/feature elsewhere.  Also, if your primary test file is named something like `test.el`, then please consider renaming that too (same for any other utility elisp files your repositoroy may contain).

Thanks!

PS: This issue is a bit generic because I had to open 69 issues.

**Comment by syohex** [comment]
Thanks for information. I have removed code `(provide 'test-helper)`.

**Comment by tarsius** [comment]
Doing just that, Emacs might still attempt to load your library instead of another. The only difference would be that now the error would be something along the line "Feature test-helper not provided".

**Comment by syohex** [comment]
- Test files are not bundled in MELPA package
- `load-path` does not have test directories usually. On my package, test files are in `test` directory, not top directory.
- Tests should be run with minimum configuration. On my package, `make test` run tests with minimum configuration
- `test-helper` should not be loaded by `require`, `-l` command line flag should be used instead.

**Comment by syohex** [comment]
BTW `ert-runner` uses  `test-helper.el` for helper functions. If it is renamed, tests which uses `ert-runner` may not work correctly.

**Comment by tarsius** [comment]
> test-helper should not be loaded by require, -l command line flag should be used instead.

Alright, not providing the feature is certainly better than providing it. This is good enough for me, even though I would still prefer if you could add a prefix.

> Test files are not bundled in MELPA package

But they are part of the repository and my [`borg`](https://github.com/emacscollective/borg) package manager installs package by adding their repositories as git submodules. However it does not add every directory that contains elisp files to the `load-path`. Instead it adds `./lisp` if that exists, else `./`. So this doesn't mess with `borg`. But someone who installs packages manually might use `normal-top-level-add-subdirs-to-load-path`. Same for other alternative package managers.

> Test files are not bundled in MELPA package

Not everyone uses Melpa packages (see above). As part of my work on the Emacsmirror I try to resolve all feature conflicts. It might be nitpicking, but speaking of Melpa, so is insisting of having libraries end with `;;; filename.el ends here`. ;-)

**Comment by tarsius** [comment]
> BTW ert-runner uses test-helper.el for helper functions. If it is renamed, tests which uses ert-runner may not work correctly.

Uh uh. Have to look into that.

**Comment by tarsius** [comment]
I am posting the following on all these issues now. Thanks for pointing this out to me before ~~anybody~~ many made the suggested change.

---

I've been informed, that `ert-runner` automatically loads the `test-helper.el` file. So you should **not** rename that file. Instead please see [this issue](https://github.com/rejeep/ert-runner.el/issues/38), where I suggest that the `(provide 'test-helper)` should be dropped instead. Please accept my apologize for opening these issues prematurely.
